[project]
name = "readmission-risk-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Julian Pulawski", email = "s31873@pjwstk.edu.pl" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
readmission-risk-service = "readmission_risk_service:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.1",
]
